version: "3.7"

volumes:
  gocache:
  emscripten:

services:
  sandbox:
    image: sandbox:sandbox
    build:
      context: images/sandbox
      args:
        - USER
        - GROUP
        - UID
        - GID
        - DOCKER_GID
    hostname: sandbox
    environment:
      - GOPROXY=http://goproxy:8081
    volumes:
      - ./.go:/go
      - ./app:/app
      - ./qt:/qt
      - emscripten:/emscripten
    stdin_open: yes
    tty: yes
    depends_on:
      - goproxy

  goproxy:
    image: goproxy/goproxy
    volumes:
      - gocache:/go
