version: "3.7"

# volumes:
#   jsdata:
#   linuxdata:
#   wasmdata:

services:
  deploy_js:
    image: sandbox/deployjs
    build:
      context: images/deployjs
    environment:
      GO111MODULE: "off"
    volumes:
      - ./app:/app
    #  - jsdata:/home/user/work

  deploy_linux:
    image: sandbox/deploylinux
    build:
      context: images/deploylinux
    environment:
      GO111MODULE: "on"
    volumes:
      - ./app:/app
      #- linuxdata:/home/user/work

  deploy_wasm:
    image: sandbox/deploywasm
    build:
      context: images/deploywasm
    environment:
      GO111MODULE: "on"
    volumes:
      - ./app:/app
    #   - wasmdata:/home/user/work
