version: "3.7"

networks:
  demonet:

services:
  go:
    image: go-sandbox:sandbox
    build:
      context: .
      dockerfile: images/go-sandbox/Dockerfile
      args:
        - USER
        - GROUP
        - UID
        - GID
        - DOCKER_GID
    hostname: go-sandbox
    environment:
      - GOPROXY=http://goproxy:8081
      - GOOS=linux
      - GOARCH=amd64
      - GO111MODULE=on
    volumes:
      - ./:/app
    stdin_open: yes
    tty: yes
    networks:
      - demonet
    depends_on:
      - goproxy

  goproxy:
    image: goproxy/goproxy
    build:
      context: images/goproxy
      args:
        - USER
        - UID
        - GID
    networks:
      - demonet
    ports:
      - 8081
    environment:
      - GOPATH=/go
    volumes:
      - ./.cache:/go
