version: "3.7"

volumes:
  gocache:

services:
  go:
    image: go-sandbox:sandbox
    build:
      context: .
      dockerfile: images/go-sandbox/Dockerfile
      args:
        - USER
        - GROUP
        - UID
        - GID
        - DOCKER_GID
    hostname: go-sandbox
    environment:
      - GOPROXY=http://goproxy:8081
      - GOOS=linux
      - GOARCH=amd64
      - GO111MODULE=on
    volumes:
      - ./.go:/go
      - ./app:/app
      - ./qt:/qt
    stdin_open: yes
    tty: yes
    depends_on:
      - goproxy

  goproxy:
    image: goproxy/goproxy
    volumes:
      - gocache:/go
