version: "3.7"

services:
  deploy_js:
    image: sandbox/deployjs
    build:
      context: images/deployjs
    environment:
      GO111MODULE: "off"
    volumes:
      - ./app:/app

  deploy_linux:
    image: sandbox/deploylinux
    build:
      context: images/deploylinux
    environment:
      GO111MODULE: "off"
    volumes:
      - ./app:/app
      - ./deploy:/deploy # Reusing the container for serving.

  deploy_wasm:
    image: sandbox/deploywasm
    build:
      context: images/deploywasm
    environment:
      GO111MODULE: "off"
    volumes:
      - ./app:/app
